# Generated by Django 2.1.15 on 2020-04-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePaperGenerator', '0003_auto_20200420_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
