# Generated by Django 2.1.15 on 2020-04-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePaperGenerator', '0004_auto_20200420_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(default=''),
        ),
    ]
