# Generated by Django 2.1.15 on 2020-04-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePaperGenerator', '0007_auto_20200421_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
