# Generated by Django 2.1.15 on 2020-04-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePaperGenerator', '0008_auto_20200421_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sem',
        ),
    ]
