# Generated by Django 2.1.15 on 2020-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OnlinePaperGenerator', '0010_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_code', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
                ('faculty', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
