# Generated by Django 2.1.15 on 2020-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePaperGenerator', '0011_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
