# Generated by Django 2.1.15 on 2020-04-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePaperGenerator', '0012_auto_20200424_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
