# Generated by Django 2.1.15 on 2020-04-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePaperGenerator', '0015_auto_20200425_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questionbank',
        ),
    ]
