# Generated by Django 2.1.15 on 2020-04-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePaperGenerator', '0016_delete_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.IntegerField(default=0)),
                ('chapterno', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('difficulty', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
