# Generated by Django 2.1.15 on 2020-04-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePaperGenerator', '0017_questionbank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questionbank',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
